# Generated by Django 2.0.6 on 2018-10-16 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retiro', '0001_initial'),
        ('producto', '0002_auto_20181016_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='retiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retiro.retiro'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='accesorio',
            field=models.ManyToManyField(to='producto.accesorio'),
        ),
    ]
