# Generated by Django 2.0.6 on 2018-10-17 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('retiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_articulo', models.CharField(max_length=60)),
                ('talla', models.CharField(max_length=3)),
                ('color', models.CharField(max_length=20)),
                ('fecha_llegada', models.DateField()),
                ('retiro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='retiro.retiro')),
            ],
        ),
    ]
