# Generated by Django 2.0.6 on 2018-10-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='accesorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='articulo',
            name='accesorio',
            field=models.ManyToManyField(to='articulo.accesorio'),
        ),
    ]
