# Generated by Django 2.0.6 on 2018-10-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='retiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('numero_id_pedido', models.CharField(max_length=10)),
                ('fecha_pedido', models.DateField()),
                ('telefono', models.CharField(max_length=12)),
                ('mail', models.EmailField(max_length=254)),
                ('web', models.CharField(max_length=50)),
            ],
        ),
    ]
